# Form implementation generated from reading ui file '.\game_start_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_team_home = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_team_home.setGeometry(QtCore.QRect(90, 90, 71, 41))
        self.label_team_home.setObjectName("label_team_home")
        self.label_team_away = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_team_away.setGeometry(QtCore.QRect(340, 90, 71, 31))
        self.label_team_away.setObjectName("label_team_away")
        self.label_scorry = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_scorry.setGeometry(QtCore.QRect(200, 10, 91, 41))
        self.label_scorry.setObjectName("label_scorry")
        self.combo_home = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_home.setGeometry(QtCore.QRect(90, 130, 68, 22))
        self.combo_home.setObjectName("combo_home")
        self.combo_away = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_away.setGeometry(QtCore.QRect(340, 130, 68, 22))
        self.combo_away.setObjectName("combo_away")
        self.start_home_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_home_button.setGeometry(QtCore.QRect(210, 180, 75, 24))
        self.start_home_button.setObjectName("start_home_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_team_home.setText(_translate("MainWindow", "Team Home"))
        self.label_team_away.setText(_translate("MainWindow", "Team Away"))
        self.label_scorry.setText(_translate("MainWindow", "Scory App"))
        self.start_home_button.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
